Feature/numeric state condition
SKAVALT-io/esidom pull request #49
Opened 2021-02-24 16:23 UTC by Lukyio

2021-02-24 16:42 UTC, souziel requested changes
Can you use the i18n for strings in the code please?

2021-02-24 16:44 UTC, Lukyio commented
> 
> 
> Can you use the i18n for strings in the code please?

Which line for example ?

2021-02-24 18:19 UTC, souziel commented on client/src/routes/automation/esidomBlocks.ts
> +                            name: 'Hour',
here i18n

2021-02-24 18:22 UTC, souziel commented on client/src/services/blocklyService.ts
> +                        tooltip: 'Après avoir fourni un capteur numérique, indiquez les valeurs minimum et maximum entre lesquelles le bloc doit/ne doit pas réagir',
here i18n

2021-02-25 16:20 UTC, Nailykk commented
> 
> 
> Can you use the i18n for strings in the code please?

Done (and more)

2021-02-25 16:47 UTC, souziel approved these changes

2021-02-25 16:47 UTC, Nailykk approved these changes

2021-02-25 16:47 UTC, merged